version: 2

models:
  - name: stg_actors
    columns:
      - name: id
        tests:
          - unique
  - name: fact_rentals
    columns:
      - name: id
        tests:
          - not_null
      - name: rental_date
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: id
      - name: staff_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_staff')
              field: id
      - name: film_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_films')
              field: id
  - name: dim_customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: dim_films
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: dim_stores
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: manager_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_staff')
              field: id

