version: 2

models:
  - name: stg_actors
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: fact_rentals
    columns:
      - name: id
        tests:
          - not_null
      - name: rental_date
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: id
      - name: staff_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_staff')
              field: id
      - name: film_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_films')
              field: id
